<?php

namespace Tests\Unit\Services\RecipeComments;

use App\Services\RecipeComments\CommentsService;
use PHPUnit\Framework\TestCase;

class CommentServiceTest extends TestCase
{
    private $service;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new CommentsService();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_example()
    {
        $this->service->show();
        $this->assertTrue(true);
    }
}
